# mkdocs.yml
site_name: LIF Docs
site_url: https://lif_docs.com/
nav:
  - 'Overview':
    - 'Architecture': "ARCHITECTURE.md"
  - 'Utilities':
    - 'Demos': 'utilities/demo.md'
    - 'Units': 'utilities/units.md'
    - 'Data objects': 'utilities/data_objects.md'
    - 'Settings Management': 'utilities/settings.md'
  - 'Receptive Fields':
    - 'Demos: Making Filters': 'receptive_fields/demo_making_filters.md'
    - 'Demos: Filter Functions': 'receptive_fields/demo_basic_filter_functions.md'
    - 'Filter Functions': 'receptive_fields/filter_functions.md'
    - 'Circular Variance': 'receptive_fields/circular_variance.md'
    - 'Filters (making)': 'receptive_fields/filters.md'
  - 'Stimulus': 'stimulus.md'
  - 'LGN Layer':
    - 'Receptive Field Locations': 'lgn/receptive_field_locations.md'
  - 'Spiking & Convolution':
    - 'Demos: Convolution': 'convolution_and_spiking/demo.md'
    - 'Demos: Correction': 'convolution_and_spiking/demo_corrections.md'
    - 'convolution_and_spiking/convolution_and_spiking.md'
    - 'Corrections': 'convolution_and_spiking/corrections.md'
    - 'Stanley 2012 Model': 'convolution_and_spiking/stanley_2012_feedforward_lif.md'
    - 'Stanley 2012 Model II': 'convolution_and_spiking/stanley_2012_feedforward_lif_part_2.md'
theme:
  name: "material"
  palette:
    scheme: slate
    primary: indigo
    accent: red
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
extra_css:
  - css/custom.css

plugins:
- search
- mkdocstrings:
    # watch:
    #   - ../lif
    handlers:
      python:
        selection:
          docstring_style: google
        rendering:
          show_root_heading: True
          show_root_toc_entry: False
          show_if_no_docstring: True
          show_signature_annotations: True
          separate_signature: True
          members_order: 'source'
markdown_extensions:
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      # macro-file: macros.tex
  - pymdownx.highlight:
  - pymdownx.superfences:

